<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day012sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [2]:
#1 Display the employ whose employee_id is 1 AND department_id is 1.
run_sql("""SELECT *
FROM employees
WHERE employee_id = 1
AND department_id = 1""")

,employee_id,first_name,last_name,department_id,hire_date,salary,job_title,city,email
0,1,Aarav,Patel,1,2020-07-10,47500.0,HR Executive,Chennai,aarav.patel1@company.com

In [3]:
#2 Display product where category is 'Electronics' AND price is greater than 1000.
run_sql("""SELECT *
FROM products
WHERE category = 'Electronics'
AND price > 1000;""")

Empty DataFrame
Columns: [product_id, product_name, category, price, stock_quantity]
Index: []

In [4]:
#3 Display customers whose city is 'Bangalore' AND customer_id is greater than 2.
run_sql("""SELECT *
FROM customers
WHERE city  = 'Bangalore'
AND customer_id > 2;""")

   customer_id first_name last_name              email       phone       city
0           11      Akash     Patel   akash11@mail.com  9719551111  Bangalore
1           16     Anjali     Singh  anjali16@mail.com  9118811611  Bangalore

In [6]:
#4 Display orders where customer_id is 1 AND employee_id is 2.
run_sql("""SELECT *
FROM orders
WHERE customer_id = 1
AND product_id = 2;""")

Empty DataFrame
Columns: [order_id, customer_id, product_id, order_date, quantity]
Index: []

In [8]:
#5 Display first_name, last_name,and email of employees whose department_id is 2 AND employee_id greater than 3.
run_sql("""SELECT first_name, last_name, email
FROM employees
WHERE department_id = 2
AND employee_id > 3;""")

  first_name last_name                     email
0     Olivia       Roy  olivia.roy12@company.com
1       Isha       Roy    isha.roy22@company.com

In [11]:
# Bonus Challenge
run_sql("""SElECT *
FROM employees
WHERE department_id = 2
AND salary > 50000;""")

,employee_id,first_name,last_name,department_id,hire_date,salary,job_title,city,email
0,2,Vivaan,Patel,2,2022-01-10,105000.0,Accountant,Bangalore,vivaan.patel2@company.com
1,22,Isha,Roy,2,2022-08-14,60000.0,Accountant,Hyderabad,isha.roy22@company.com