<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day046sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [ ]:
# Topic: Advanced GROUP BY & HAVING Practice

In [ ]:
#1.
run_sql("""SELECT department_id, COUNT(*) AS total_employees
FROM employees
GROUP BY department_id
HAVING COUNT(*) >= 3;""")

   department_id  total_employees
0              1                3
1              2                3
2              3                3
3              4                3
4              5                3
5              6                3
6              7                3
7              8                3
8              9                3
9             10                3

In [ ]:
#2.
run_sql("""SELECT category, AVG(price) AS average_price
FROM products
GROUP BY category
HAVING AVG(price) > 750;""")

     category  average_price
0      Camera        46499.0
1  Headphones         6249.0
2    Keyboard         3249.0
3      Laptop        91249.0
4      Mobile        31249.0
5     Monitor        17249.0
6       Mouse         2249.0

In [ ]:
#3.
run_sql("""SELECT customer_id, SUM(quantity) AS total_quantity
FROM orders
WHERE quantity > 1
GROUP BY customer_id
HAVING SUM(quantity) > 10;""")

   customer_id  total_quantity
0            9              17
1           13              15
2           14              12
3           15              17
4           16              12
5           20              11
6           24              15
7           32              18
8           34              15
9           35              15

In [ ]:
#4.
run_sql("""SELECT department_id,
                   MIN(salary) AS minimum_salary,
                   MAX(salary) AS maximum_salary,
                   AVG(salary) AS average_salary
        FROM employees
        WHERE salary > 30000
        GROUP BY department_id
        HAVING MAX(salary) > 80000;""")

   department_id  minimum_salary  maximum_salary  average_salary
0              1         42500.0        112500.0    67500.000000
1              2         50000.0        105000.0    71666.666667
2              3         45000.0        105000.0    85000.000000
3              4         97500.0        117500.0   109166.666667
4              5         57500.0        120000.0    83333.333333
5              6         67500.0        117500.0    98333.333333
6              7         52500.0         90000.0    67500.000000
7              8         40000.0        105000.0    65000.000000
8             10         85000.0        120000.0   100833.333333

In [ ]:
#5.
run_sql("""SELECT category,
        SUM(stock_quantity) AS total_stock_quantity,
        MIN(price) AS minimum_price,
        MAX(price) AS maximum_price,
        AVG(price) AS average_price

        FROM products
        WHERE price > 500
        GROUP BY category
        HAVING SUM(stock_quantity) > 100;""")

,category,total_stock_quantity,minimum_price,maximum_price,average_price
0,Headphones,165,5499.0,6999.0,6249.0
1,Keyboard,170,2499.0,3999.0,3249.0

In [16]:
# Bonus Challege
run_sql("""SELECT customer_id,
        COUNT(*) AS total_orders,
        AVG(quantity) AS average_order_quantity
        FROM orders
        GROUP BY customer_id
        HAVING COUNT(*) > 2;""")

    customer_id  total_orders  average_order_quantity
0             2             3                3.333333
1             3             3                1.333333
2             4             3                2.333333
3             5             3                3.333333
4             8             3                2.333333
5             9             4                4.250000
6            11             3                2.000000
7            13             6                2.666667
8            14             5                2.800000
9            15             5                3.400000
10           16             5                2.600000
11           20             3                3.666667
12           24             3                5.000000
13           25             3                3.000000
14           26             4                2.500000
15           28             3                1.666667
16           29             3                3.000000
17           32             7                2.857143
18           34             8                2.375000
19           35             5                3.200000