<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day019sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [1]:
# Topic: Business-style filtering practice using WHERE operator.

In [5]:
#1 Display all employees whose employee_id is BETWEEN 2 AND 6.
run_sql("""SELECT *
FROM employees
WHERE employee_id BETWEEN 2 AND 6;""")

,employee_id,first_name,last_name,department_id,hire_date,salary,job_title,city,email
0,2,Vivaan,Patel,2,2022-01-10,105000.0,Accountant,Bangalore,vivaan.patel2@company.com
1,3,Aditya,Das,3,2021-11-02,45000.0,Software Engineer,Delhi,aditya.das3@company.com
2,4,Riya,Das,4,2024-02-16,117500.0,Marketing Executive,Delhi,riya.das4@company.com
3,5,Priya,Das,5,2020-01-29,120000.0,Sales Executive,Mumbai,priya.das5@company.com
4,6,Neha,Taylor,6,2024-11-24,67500.0,Operations Analyst,Hyderabad,neha.taylor6@company.com

In [6]:
#2 Display customer whosecity inIN('Delhi',Mumbai').
run_sql("""SELECT *
FROM customers
WHERE city IN ('Delhi', 'Mumbai');""")

   customer_id first_name last_name              email       phone    city
0            3      Mohit     Kumar    mohit3@mail.com  9208428912  Mumbai
1            8      Komal       Roy    komal8@mail.com  9467566361   Delhi
2           12       Ritu     Kumar    ritu12@mail.com  9658448295   Delhi
3           20      Aisha     Kumar   aisha20@mail.com  9659589923   Delhi
4           26     Anjali     Kumar  anjali26@mail.com  9988357959   Delhi
5           27     Deepak    Sharma  deepak27@mail.com  9922832851   Delhi
6           28      Komal     Singh   komal28@mail.com  9110051432  Mumbai
7           30      Aisha       Das   aisha30@mail.com  9627755893  Mumbai
8           33      Mohit       Roy   mohit33@mail.com  9665152033   Delhi

In [7]:
#3 Display products whose category whose categoryis NOT 'Furniture' AND price is BETWEEN 500 AND 5000.
run_sql("""SELECT *
FROM products
WHERE category NOT IN ('Furniture')
 AND price BETWEEN 500 AND 5000;""")

   product_id      product_name  category   price  stock_quantity
0          17  Keyboard Model 1  Keyboard  2499.0              80
1          18  Keyboard Model 2  Keyboard  2999.0              35
2          19  Keyboard Model 3  Keyboard  3499.0               5
3          20  Keyboard Model 4  Keyboard  3999.0              50
4          21     Mouse Model 1     Mouse  1499.0               0
5          22     Mouse Model 2     Mouse  1999.0              20
6          23     Mouse Model 3     Mouse  2499.0              35
7          24     Mouse Model 4     Mouse  2999.0               0

In [9]:
#4 Display orders where customer_id IN (1,2,3) AND employee_id IN (1,2).
run_sql("""SELECT *
FROM orders
WHERE customer_id IN (1,2,3)
 AND product_id IN (1,2);""")

   order_id  customer_id  product_id  order_date  quantity
0        89            3           1  2026-03-29         1

In [10]:
#5 Display employee_id, first_name, and last_name for employees whose department_id is 2 OR 3, but whose employee_id is NOT BETWEEN 1 AND 2.
run_sql("""SELECT employee_id, first_name, last_name
FROM employees
WHERE (department_id =2 OR department_id =3)
 AND employee_id NOT BETWEEN 1 AND 2;""")

   employee_id first_name last_name
0            3     Aditya       Das
1           12     Olivia       Roy
2           13       Liam     Singh
3           22       Isha       Roy
4           23      Kabir    Sharma

In [13]:
# Bonus Challenge
run_sql("""SELECT *
FROM products
WHERE category IN ('Electronic', 'Clothing')
  AND price BETWEEN 1000 AND 10000;""")

Empty DataFrame
Columns: [product_id, product_name, category, price, stock_quantity]
Index: []