<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day035sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [4]:
# Topic: Learn how to calculate the average value of numeric data using AVG().

In [5]:
# Find the average salary of all employees.
run_sql("""SELECT AVG(salary) AS average_salary
FROM employees;""")

   average_salary
0         80750.0

In [6]:
#2 Find the avergare price of all products.
run_sql("""SELECT AVG(price) AS average_price
FROM products;""")

   average_price
0        26099.0

In [7]:
#3 Find the average quantity orderd in the orders table.
run_sql("""SELECT AVG(quantity) AS average_quantity
FROM orders;""")

   average_quantity
0              2.93

In [8]:
#4 Find the average salary of employees whose deaprtment_id is 2.
run_sql("""SELECT AVG(salary)
FROM employees
WHERE department_id = 2;""")

    AVG(salary)
0  71666.666667

In [10]:
#5 Find the average price of products in the Electronics category.
run_sql("""SELECT AVG(price) AS average_price
FROM products
WHERE category = 'Electronic';""")

  average_price
0          None

In [11]:
# Bonus Challege
run_sql("""SELECT AVG(stock_quantity) AS average_stock_quantity
FROM products
WHERE stock_quantity > 50;""")

   average_stock_quantity
0                    80.0