<a href="https://colab.research.google.com/github/surbhi-codehub/100-Days-SQL-Journey/blob/main/day07sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [2]:
#1
run_sql("""SELECT employee_id ,last_name
FROM employees
LIMIT 5;""")

   employee_id last_name
0            1     Patel
1            2     Patel
2            3       Das
3            4       Das
4            5       Das

In [3]:
#2
run_sql("""SELECT department_id, department_name
FROM departments
LIMIT 3;""")

   department_id department_name
0              1              HR
1              2         Finance
2              3              IT

In [4]:
#3
run_sql("""SELECT product_name,category,price
FROM products
LIMIT 5;""")

     product_name category    price
0  Laptop Model 1   Laptop  90499.0
1  Laptop Model 2   Laptop  90999.0
2  Laptop Model 3   Laptop  91499.0
3  Laptop Model 4   Laptop  91999.0
4  Mobile Model 1   Mobile  30499.0

In [6]:
#4
run_sql("""SELECT customer_id, first_name,email
FROM customers
LIMIT 5;""")

   customer_id first_name             email
0            1      Akash   akash1@mail.com
1            2       Ritu    ritu2@mail.com
2            3      Mohit   mohit3@mail.com
3            4     Simran  simran4@mail.com
4            5       Yash    yash5@mail.com

In [10]:
#5
run_sql("""SELECT order_id, order_date, customer_id
FROM orders
LIMIT 10;""")

   order_id  order_date  customer_id
0         1  2025-10-15           20
1         2  2025-02-26           11
2         3  2024-01-15           29
3         4  2024-09-08           17
4         5  2024-12-14           16
5         6  2025-09-01           15
6         7  2024-05-15            2
7         8  2026-03-11           13
8         9  2025-01-10           28
9        10  2024-07-16            1

In [11]:
# Bonus challenge
run_sql("""SELECT employee_id,first_name, email
FROM employees
LIMIT 8;""")

   employee_id first_name                      email
0            1      Aarav   aarav.patel1@company.com
1            2     Vivaan  vivaan.patel2@company.com
2            3     Aditya    aditya.das3@company.com
3            4       Riya      riya.das4@company.com
4            5      Priya     priya.das5@company.com
5            6       Neha   neha.taylor6@company.com
6            7      Rahul     rahul.roy7@company.com
7            8       Amit      amit.roy8@company.com