<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day037sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [2]:
# Learn how to find the largest value in a numeric or data column using MAX().

In [3]:
#1 Find the highest salary among all employees.
run_sql("""SELECT MAX(salary) AS highest_salary
FROM  employees;""")

   highest_salary
0        120000.0

In [4]:
#2 Find the maximum product price.
run_sql("""SELECT MAX(price) AS maximum_price
FROM products;""")

   maximum_price
0        91999.0

In [5]:
#3 Find the latest order date in the orders table.
run_sql("""SELECT MAX(order_date) AS latest_order_date
FROM orders;""")

  latest_order_date
0        2026-05-02

In [6]:
#4 Find the highest stock quantity for products in the Electronics category.
run_sql("""SELECT MAX(stock_quantity) AS highest_stock_quantity
FROM products
WHERE category = 'Electronics';""")

  highest_stock_quantity
0                   None

In [8]:
#5 Find the highest salary of employees whose department_id is 2.
run_sql("""SELECT MAX(salary) AS higest_salary
FROM employees
WHERE department_id = 2;""")

   higest_salary
0       105000.0

In [9]:
# Bonus Challege
run_sql("""SELECT MAX(hire_date) AS latest_hire_date
FROM employees
WHERE salary > 50000;""")

  latest_hire_date
0       2024-11-24