<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day022sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [2]:
#1 Display all department sorted by department_name in descending order.
run_sql("""SELECT*
FROM departments
ORDER BY department_name DESC;""")

   department_id   department_name  manager_id   location    budget
0              7           Support           7    Chennai  250000.0
1             10          Security          10    Kolkata  220000.0
2              5             Sales           5  Hyderabad  700000.0
3              6        Operations           6       Pune  500000.0
4              4         Marketing           4      Delhi  350000.0
5              8             Legal           8      Delhi  280000.0
6              3                IT           3  Bangalore  900000.0
7              1                HR           1  Bangalore  300000.0
8              2           Finance           2     Mumbai  450000.0
9              9  Data Engineering           9  Bangalore  800000.0

In [3]:
#2 Display employees sorted by first_name indescending order.
run_sql("""SELECT *
FROM employees
ORDER BY first_name DESC;""")

,employee_id,first_name,last_name,department_id,hire_date,salary,job_title,city,email
0,2,Vivaan,Patel,2,2022-01-10,105000.0,Accountant,Bangalore,vivaan.patel2@company.com
1,25,Vikram,Roy,5,2024-11-20,57500.0,Sales Executive,Pune,vikram.roy25@company.com
2,14,Sophia,Roy,4,2022-01-01,97500.0,Marketing Executive,Delhi,sophia.roy14@company.com
3,18,Sneha,Sharma,8,2020-01-20,50000.0,Legal Advisor,Bangalore,sneha.sharma18@company.com
4,20,Sara,Taylor,10,2023-12-21,85000.0,Security Analyst,Delhi,sara.taylor20@company.com
5,17,Rohan,Singh,7,2022-04-21,52500.0,Support Engineer,Mumbai,rohan.singh17@company.com
6,4,Riya,Das,4,2024-02-16,117500.0,Marketing Executive,Delhi,riya.das4@company.com
7,7,Rahul,Roy,7,2019-02-23,90000.0,Support Engineer,Mumbai,rahul.roy7@company.com
8,5,Priya,Das,5,2020-01-29,120000.0,Sales Executive,Mumbai,priya.das5@company.com
9,30,Pooja,Sharma,10,2020-05-02,120000.0,Security Analyst,Pune,pooja.sharma30@company.com
10,12,Olivia,Roy,2,2021-02-05,50000.0,Accountant,Bangalore,olivia.roy12@company.com
11,11,Noah,Singh,1,2023-04-11,112500.0,HR Executive,Delhi,noah.singh11@company.com
12,26,Nisha,Sharma,6,2023-08-06,110000.0,Operations Analyst,Pune,nisha.sharma26@company.com
13,6,Neha,Taylor,6,2024-11-24,67500.0,Operations Analyst,Hyderabad,neha.taylor6@company.com
14,24,Meera,Singh,4,2021-07-03,112500.0,Marketing Executive,Hyderabad,meera.singh24@company.com
15,13,Liam,Singh,3,2020-10-03,105000.0,Software Engineer,Mumbai,liam.singh13@company.com
16,16,Karan,Taylor,6,2021-01-27,117500.0,Operations Analyst,Pune,karan.taylor16@company.com
17,23,Kabir,Sharma,3,2023-05-02,105000.0,Software Engineer,Mumbai,kabir.sharma23@company.com
18,9,John,Brown,9,2021-11-22,45000.0,Data Engineer,Pune,john.brown9@company.com
19,22,Isha,Roy,2,2022-08-14,60000.0,Accountant,Hyderabad,isha.roy22@company.com
20,28,Grace,Brown,8,2023-03-29,40000.0,Legal Advisor,Bangalore,grace.brown28@company.com
21,10,Emma,Kumar,10,2023-07-25,97500.0,Security Analyst,Kolkata,emma.kumar10@company.com
22,19,David,Singh,9,2021-04-21,62500.0,Data Engineer,Pune,david.singh19@company.com
23,27,Daniel,Roy,7,2023-05-29,60000.0,Support Engineer,Pune,daniel.roy27@company.com
24,29,Aryan,Das,9,2022-12-19,70000.0,Data Engineer,Hyderabad,aryan.das29@company.com
25,21,Arjun,Taylor,1,2021-09-03,42500.0,HR Executive,Bangalore,arjun.taylor21@company.com
26,15,Ananya,Singh,5,2022-08-02,72500.0,Sales Executive,Kolkata,ananya.singh15@company.com
27,8,Amit,Roy,8,2021-05-07,105000.0,Legal Advisor,Bangalore,amit.roy8@company.com
28,3,Aditya,Das,3,2021-11-02,45000.0,Software Engineer,Delhi,aditya.das3@company.com
29,1,Aarav,Patel,1,2020-07-10,47500.0,HR Executive,Chennai,aarav.patel1@company.com

In [4]:
# Display products sorted by price from higest to lowest.
run_sql("""SELECT *
FROM products
ORDER BY price DESC;""")

    product_id        product_name    category    price  stock_quantity
0            4      Laptop Model 4      Laptop  91999.0               5
1            3      Laptop Model 3      Laptop  91499.0              50
2            2      Laptop Model 2      Laptop  90999.0               0
3            1      Laptop Model 1      Laptop  90499.0              35
4           25      Camera Model 1      Camera  46499.0               0
5            8      Mobile Model 4      Mobile  31999.0               0
6            7      Mobile Model 3      Mobile  31499.0              12
7            6      Mobile Model 2      Mobile  30999.0               0
8            5      Mobile Model 1      Mobile  30499.0              35
9           16     Monitor Model 4     Monitor  17999.0              20
10          15     Monitor Model 3     Monitor  17499.0               5
11          14     Monitor Model 2     Monitor  16999.0               0
12          13     Monitor Model 1     Monitor  16499.0              20
13          12  Headphones Model 4  Headphones   6999.0               5
14          11  Headphones Model 3  Headphones   6499.0              80
15          10  Headphones Model 2  Headphones   5999.0               0
16           9  Headphones Model 1  Headphones   5499.0              80
17          20    Keyboard Model 4    Keyboard   3999.0              50
18          19    Keyboard Model 3    Keyboard   3499.0               5
19          18    Keyboard Model 2    Keyboard   2999.0              35
20          24       Mouse Model 4       Mouse   2999.0               0
21          17    Keyboard Model 1    Keyboard   2499.0              80
22          23       Mouse Model 3       Mouse   2499.0              35
23          22       Mouse Model 2       Mouse   1999.0              20
24          21       Mouse Model 1       Mouse   1499.0               0

In [8]:
#4 Display customers sorted by customer_name inreverse alphabetical order.
run_sql("""SELECT *
FROM customers
ORDER BY first_name DESC;""")

    customer_id first_name last_name              email       phone       city
0             5       Yash    Sharma     yash5@mail.com  9426111115       Pune
1            15       Yash    Sharma    yash15@mail.com  9702952921  Hyderabad
2            25       Yash     Singh    yash25@mail.com  9834197053       Pune
3            35       Yash       Das    yash35@mail.com  9847568100  Hyderabad
4             4     Simran       Das   simran4@mail.com  9979444461    Chennai
5            14     Simran    Taylor  simran14@mail.com  9604314504    Kolkata
6            24     Simran       Das  simran24@mail.com  9185583902       Pune
7            34     Simran    Wilson  simran34@mail.com  9642604350       Pune
8             2       Ritu       Das     ritu2@mail.com  9627404182  Bangalore
9            12       Ritu     Kumar    ritu12@mail.com  9658448295      Delhi
10           22       Ritu     Kumar    ritu22@mail.com  9882449902  Hyderabad
11           32       Ritu    Sharma    ritu32@mail.com  9787498671    Chennai
12            9      Nitin     Brown    nitin9@mail.com  9899533704  Hyderabad
13           19      Nitin    Taylor   nitin19@mail.com  9995653703  Hyderabad
14           29      Nitin    Wilson   nitin29@mail.com  9200774016  Hyderabad
15           39      Nitin       Das   nitin39@mail.com  9759424149    Chennai
16            3      Mohit     Kumar    mohit3@mail.com  9208428912     Mumbai
17           13      Mohit       Das   mohit13@mail.com  9361812679  Hyderabad
18           23      Mohit    Taylor   mohit23@mail.com  9744597750    Kolkata
19           33      Mohit       Roy   mohit33@mail.com  9665152033      Delhi
20            8      Komal       Roy    komal8@mail.com  9467566361      Delhi
21           18      Komal     Singh   komal18@mail.com  9504584808    Kolkata
22           28      Komal     Singh   komal28@mail.com  9110051432     Mumbai
23           38      Komal       Roy   komal38@mail.com  9634822466    Chennai
24            7     Deepak    Wilson   deepak7@mail.com  9906274295  Hyderabad
25           17     Deepak    Taylor  deepak17@mail.com  9865412201  Hyderabad
26           27     Deepak    Sharma  deepak27@mail.com  9922832851      Delhi
27           37     Deepak    Wilson  deepak37@mail.com  9413891625       Pune
28            6     Anjali     Singh   anjali6@mail.com  9693986973       Pune
29           16     Anjali     Singh  anjali16@mail.com  9118811611  Bangalore
30           26     Anjali     Kumar  anjali26@mail.com  9988357959      Delhi
31           36     Anjali     Gupta  anjali36@mail.com  9310837702    Chennai
32            1      Akash    Sharma    akash1@mail.com  9666696518  Bangalore
33           11      Akash     Patel   akash11@mail.com  9719551111  Bangalore
34           21      Akash    Sharma   akash21@mail.com  9124393190       Pune
35           31      Akash     Gupta   akash31@mail.com  9750806415    Kolkata
36           10      Aisha     Kumar   aisha10@mail.com  9332083015    Chennai
37           20      Aisha     Kumar   aisha20@mail.com  9659589923      Delhi
38           30      Aisha       Das   aisha30@mail.com  9627755893     Mumbai
39           40      Aisha    Taylor   aisha40@mail.com  9829603810    Kolkata

In [6]:
#5 Display orders sorted by order_date from newest to oldest.
run_sql("""SELECT *
FROM orders
ORDER BY order_date DESC;""")

    order_id  customer_id  product_id  order_date  quantity
0         78           25           8  2026-05-02         3
1         13           14          17  2026-04-14         5
2         58           30           1  2026-04-06         4
3         36           14           4  2026-04-04         3
4         89            3           1  2026-03-29         1
..       ...          ...         ...         ...       ...
95        14           33          19  2024-01-19         1
96         3           29          24  2024-01-15         3
97        53           29           4  2024-01-15         1
98        34           35          11  2024-01-12         4
99        59           28           4  2024-01-07         1

[100 rows x 5 columns]

In [7]:
# Bonus Challenge
run_sql("""SELECT *
FROM employees
ORDER BY employee_id DESC;""")

,employee_id,first_name,last_name,department_id,hire_date,salary,job_title,city,email
0,30,Pooja,Sharma,10,2020-05-02,120000.0,Security Analyst,Pune,pooja.sharma30@company.com
1,29,Aryan,Das,9,2022-12-19,70000.0,Data Engineer,Hyderabad,aryan.das29@company.com
2,28,Grace,Brown,8,2023-03-29,40000.0,Legal Advisor,Bangalore,grace.brown28@company.com
3,27,Daniel,Roy,7,2023-05-29,60000.0,Support Engineer,Pune,daniel.roy27@company.com
4,26,Nisha,Sharma,6,2023-08-06,110000.0,Operations Analyst,Pune,nisha.sharma26@company.com
5,25,Vikram,Roy,5,2024-11-20,57500.0,Sales Executive,Pune,vikram.roy25@company.com
6,24,Meera,Singh,4,2021-07-03,112500.0,Marketing Executive,Hyderabad,meera.singh24@company.com
7,23,Kabir,Sharma,3,2023-05-02,105000.0,Software Engineer,Mumbai,kabir.sharma23@company.com
8,22,Isha,Roy,2,2022-08-14,60000.0,Accountant,Hyderabad,isha.roy22@company.com
9,21,Arjun,Taylor,1,2021-09-03,42500.0,HR Executive,Bangalore,arjun.taylor21@company.com
10,20,Sara,Taylor,10,2023-12-21,85000.0,Security Analyst,Delhi,sara.taylor20@company.com
11,19,David,Singh,9,2021-04-21,62500.0,Data Engineer,Pune,david.singh19@company.com
12,18,Sneha,Sharma,8,2020-01-20,50000.0,Legal Advisor,Bangalore,sneha.sharma18@company.com
13,17,Rohan,Singh,7,2022-04-21,52500.0,Support Engineer,Mumbai,rohan.singh17@company.com
14,16,Karan,Taylor,6,2021-01-27,117500.0,Operations Analyst,Pune,karan.taylor16@company.com
15,15,Ananya,Singh,5,2022-08-02,72500.0,Sales Executive,Kolkata,ananya.singh15@company.com
16,14,Sophia,Roy,4,2022-01-01,97500.0,Marketing Executive,Delhi,sophia.roy14@company.com
17,13,Liam,Singh,3,2020-10-03,105000.0,Software Engineer,Mumbai,liam.singh13@company.com
18,12,Olivia,Roy,2,2021-02-05,50000.0,Accountant,Bangalore,olivia.roy12@company.com
19,11,Noah,Singh,1,2023-04-11,112500.0,HR Executive,Delhi,noah.singh11@company.com
20,10,Emma,Kumar,10,2023-07-25,97500.0,Security Analyst,Kolkata,emma.kumar10@company.com
21,9,John,Brown,9,2021-11-22,45000.0,Data Engineer,Pune,john.brown9@company.com
22,8,Amit,Roy,8,2021-05-07,105000.0,Legal Advisor,Bangalore,amit.roy8@company.com
23,7,Rahul,Roy,7,2019-02-23,90000.0,Support Engineer,Mumbai,rahul.roy7@company.com
24,6,Neha,Taylor,6,2024-11-24,67500.0,Operations Analyst,Hyderabad,neha.taylor6@company.com
25,5,Priya,Das,5,2020-01-29,120000.0,Sales Executive,Mumbai,priya.das5@company.com
26,4,Riya,Das,4,2024-02-16,117500.0,Marketing Executive,Delhi,riya.das4@company.com
27,3,Aditya,Das,3,2021-11-02,45000.0,Software Engineer,Delhi,aditya.das3@company.com
28,2,Vivaan,Patel,2,2022-01-10,105000.0,Accountant,Bangalore,vivaan.patel2@company.com
29,1,Aarav,Patel,1,2020-07-10,47500.0,HR Executive,Chennai,aarav.patel1@company.com