<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day039sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [2]:
# Topic: Practice with Aggregate Functions.

In [5]:
#1 Display the total number of products and the avergae product price.
run_sql("""SELECT COUNT(*) AS TOTAL_PRODUCTS,
        AVG(price) AS average_price
        FROM products;""")

   TOTAL_PRODUCTS  average_price
0              25        26099.0

In [6]:
#2 Find the total qunatity order and the maximum quantity ordered from the orders table
run_sql("""SELECT SUM(quantity) AS total_quantity,
        MAX(quantity) AS maximum_quantity
        FROM orders;""")

   total_quantity  maximum_quantity
0             293                 5

In [10]:
#3 Display the minimum , maximum and average salary of all employees.
run_sql("""SELECT MIN(salary) AS minimum_salary,
                  MAX(salary) AS maximum_salary,
                  AVG(salary) AS average_salary
           FROM employees;""");

In [15]:
#4 For the products in Electronics category , display the total number of products, total stock quantity , and average product price.
run_sql("""SELECT COUNT(*) AS total_products,
                 SUM (stock_quantity) AS total_stock,
                  AVG(price) AS average_price
            FROM products
            WHERE category = 'Electronic';""")

   total_products total_stock average_price
0               0        None          None

In [17]:
#5
run_sql("""SELECT COUNT(*) AS total_employees,
                  SUM(salary) AS total_salary,
                  AVG(salary) AS average_salary,
                  MIN(salary) AS minimum_salary,
                  MAX(salary) AS maximum_salary
         FROM employees
         WHERE department_id = 1;""")

,total_employees,total_salary,average_salary,minimum_salary,maximum_salary
0,3,202500.0,67500.0,42500.0,112500.0

In [14]:
# Bonus Challege
run_sql("""SELECT COUNT(*) AS  total_orders,
                   MIN(quantity) AS minimum_quantity,
                   MAX(quantity) AS maximum_quantity,
                   AVG(quantity) AS average_quantity
        FROM orders;""")

   total_orders  minimum_quantity  maximum_quantity  average_quantity
0           100                 1                 5              2.93