<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day047sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [3]:
# Topic: GROUP BY &HAVING - Final practice.

In [4]:
#1
run_sql("""SELECT department_id, COUNT(*) AS total_employees
FROM employees
GROUP BY department_id
HAVING COUNT(*) >= 2;""")

   department_id  total_employees
0              1                3
1              2                3
2              3                3
3              4                3
4              5                3
5              6                3
6              7                3
7              8                3
8              9                3
9             10                3

In [6]:
#2
run_sql("""SELECT category, AVG(price) AS average_price
FROM products
WHERE stock_quantity > 20
GROUP BY category
HAVING AVG(price) > 1000;""")

     category  average_price
0  Headphones    5999.000000
1    Keyboard    3165.666667
2      Laptop   90999.000000
3      Mobile   30499.000000
4       Mouse    2499.000000

In [7]:
#3
run_sql("""SELECT customer_id,
         COUNT(*) AS total_orders,
         SUM(quantity) AS total_order_quantity
         FROM orders
         GROUP BY customer_id
         HAVING SUM(quantity) > 15;""")

   customer_id  total_orders  total_order_quantity
0            9             4                    17
1           13             6                    16
2           15             5                    17
3           32             7                    20
4           34             8                    19
5           35             5                    16

In [8]:
#4
run_sql("""SELECT department_id,
         MIN(salary) AS minimum_salary,
         MAX(salary) AS maximum_salary,
         AVG(salary) AS average_salary

        FROM employees
        WHERE hire_date > '2022-01-01'
        GROUP BY department_id
        HAVING AVG(salary) > 60000;""")

   department_id  minimum_salary  maximum_salary  average_salary
0              1        112500.0        112500.0        112500.0
1              2         60000.0        105000.0         82500.0
2              3        105000.0        105000.0        105000.0
3              4        117500.0        117500.0        117500.0
4              5         57500.0         72500.0         65000.0
5              6         67500.0        110000.0         88750.0
6              9         70000.0         70000.0         70000.0
7             10         85000.0         97500.0         91250.0

In [10]:
#5
run_sql("""SELECT category,
                  SUM(stock_quantity) AS total_stock_quantity,
                  AVG(price) AS average_price,
                  MIN(price) AS minimum_price,
                  MAX(price) AS maximum_price

          FROM products
          WHERE price > 500
          GROUP BY category
          HAVING SUM(stock_quantity) > 200;""")

Empty DataFrame
Columns: [category, total_stock_quantity, average_price, minimum_price, maximum_price]
Index: []

In [14]:
# Bonus Challege
run_sql("""SELECT customer_id,
       MAX(quantity) AS maximum_order_quantiy

       FROM orders
       GROUP BY customer_id
       HAVING COUNT(*) > 2;""")

    customer_id  maximum_order_quantiy
0             2                      4
1             3                      2
2             4                      3
3             5                      4
4             8                      4
5             9                      5
6            11                      2
7            13                      5
8            14                      5
9            15                      5
10           16                      5
11           20                      5
12           24                      5
13           25                      4
14           26                      4
15           28                      3
16           29                      5
17           32                      5
18           34                      5
19           35                      5