<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day030sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [ ]:
# Topic: Final review of ORDER,LIKE,%, and_.

In [11]:
#1 Display all customers whose customer_name starts with 'A', sorted apphabetically.
run_sql("""SELECT *
FROM customers
WHERE first_name LIKE 'A%'
ORDER BY first_name ASC;""")

    customer_id first_name last_name              email       phone       city
0            10      Aisha     Kumar   aisha10@mail.com  9332083015    Chennai
1            20      Aisha     Kumar   aisha20@mail.com  9659589923      Delhi
2            30      Aisha       Das   aisha30@mail.com  9627755893     Mumbai
3            40      Aisha    Taylor   aisha40@mail.com  9829603810    Kolkata
4             1      Akash    Sharma    akash1@mail.com  9666696518  Bangalore
5            11      Akash     Patel   akash11@mail.com  9719551111  Bangalore
6            21      Akash    Sharma   akash21@mail.com  9124393190       Pune
7            31      Akash     Gupta   akash31@mail.com  9750806415    Kolkata
8             6     Anjali     Singh   anjali6@mail.com  9693986973       Pune
9            16     Anjali     Singh  anjali16@mail.com  9118811611  Bangalore
10           26     Anjali     Kumar  anjali26@mail.com  9988357959      Delhi
11           36     Anjali     Gupta  anjali36@mail.com  9310837702    Chennai

In [13]:
#2 Display employees whose first_name contains the letter 'a', sorted by first_name.
run_sql("""SELECT *
FROM employees
WHERE first_name LIKE '%a%'
ORDER BY first_name ASC;""")

,employee_id,first_name,last_name,department_id,hire_date,salary,job_title,city,email
0,1,Aarav,Patel,1,2020-07-10,47500.0,HR Executive,Chennai,aarav.patel1@company.com
1,3,Aditya,Das,3,2021-11-02,45000.0,Software Engineer,Delhi,aditya.das3@company.com
2,8,Amit,Roy,8,2021-05-07,105000.0,Legal Advisor,Bangalore,amit.roy8@company.com
3,15,Ananya,Singh,5,2022-08-02,72500.0,Sales Executive,Kolkata,ananya.singh15@company.com
4,21,Arjun,Taylor,1,2021-09-03,42500.0,HR Executive,Bangalore,arjun.taylor21@company.com
5,29,Aryan,Das,9,2022-12-19,70000.0,Data Engineer,Hyderabad,aryan.das29@company.com
6,27,Daniel,Roy,7,2023-05-29,60000.0,Support Engineer,Pune,daniel.roy27@company.com
7,19,David,Singh,9,2021-04-21,62500.0,Data Engineer,Pune,david.singh19@company.com
8,10,Emma,Kumar,10,2023-07-25,97500.0,Security Analyst,Kolkata,emma.kumar10@company.com
9,28,Grace,Brown,8,2023-03-29,40000.0,Legal Advisor,Bangalore,grace.brown28@company.com
10,22,Isha,Roy,2,2022-08-14,60000.0,Accountant,Hyderabad,isha.roy22@company.com
11,23,Kabir,Sharma,3,2023-05-02,105000.0,Software Engineer,Mumbai,kabir.sharma23@company.com
12,16,Karan,Taylor,6,2021-01-27,117500.0,Operations Analyst,Pune,karan.taylor16@company.com
13,13,Liam,Singh,3,2020-10-03,105000.0,Software Engineer,Mumbai,liam.singh13@company.com
14,24,Meera,Singh,4,2021-07-03,112500.0,Marketing Executive,Hyderabad,meera.singh24@company.com
15,6,Neha,Taylor,6,2024-11-24,67500.0,Operations Analyst,Hyderabad,neha.taylor6@company.com
16,26,Nisha,Sharma,6,2023-08-06,110000.0,Operations Analyst,Pune,nisha.sharma26@company.com
17,11,Noah,Singh,1,2023-04-11,112500.0,HR Executive,Delhi,noah.singh11@company.com
18,12,Olivia,Roy,2,2021-02-05,50000.0,Accountant,Bangalore,olivia.roy12@company.com
19,30,Pooja,Sharma,10,2020-05-02,120000.0,Security Analyst,Pune,pooja.sharma30@company.com
20,5,Priya,Das,5,2020-01-29,120000.0,Sales Executive,Mumbai,priya.das5@company.com
21,7,Rahul,Roy,7,2019-02-23,90000.0,Support Engineer,Mumbai,rahul.roy7@company.com
22,4,Riya,Das,4,2024-02-16,117500.0,Marketing Executive,Delhi,riya.das4@company.com
23,17,Rohan,Singh,7,2022-04-21,52500.0,Support Engineer,Mumbai,rohan.singh17@company.com
24,20,Sara,Taylor,10,2023-12-21,85000.0,Security Analyst,Delhi,sara.taylor20@company.com
25,18,Sneha,Sharma,8,2020-01-20,50000.0,Legal Advisor,Bangalore,sneha.sharma18@company.com
26,14,Sophia,Roy,4,2022-01-01,97500.0,Marketing Executive,Delhi,sophia.roy14@company.com
27,25,Vikram,Roy,5,2024-11-20,57500.0,Sales Executive,Pune,vikram.roy25@company.com
28,2,Vivaan,Patel,2,2022-01-10,105000.0,Accountant,Bangalore,vivaan.patel2@company.com

In [14]:
#3 Display products whose product_name ends with 'r', sorted by price indescending order.
run_sql("""SELECT *
FROM products
WHERE product_name LIKE '%r'
ORDER BY price DESC;""")

Empty DataFrame
Columns: [product_id, product_name, category, price, stock_quantity]
Index: []

In [19]:
# Display department whose department_name contains the letter 'e', sorted alphabetically.
run_sql("""SELECT *
FROM departments
WHERE department_name LIKE '%e%'
ORDER BY department_name ASC;""")

   department_id   department_name  manager_id   location    budget
0              9  Data Engineering           9  Bangalore  800000.0
1              2           Finance           2     Mumbai  450000.0
2              8             Legal           8      Delhi  280000.0
3              4         Marketing           4      Delhi  350000.0
4              6        Operations           6       Pune  500000.0
5              5             Sales           5  Hyderabad  700000.0
6             10          Security          10    Kolkata  220000.0

In [22]:
#5 Display customers whose city starts with 'B' and ends with 'e', sorted by customer_name.
run_sql("""SELECT *
FROM customers
WHERE city LIKE 'B%e'
ORDER BY first_name ASC;""")

   customer_id first_name last_name              email       phone       city
0            1      Akash    Sharma    akash1@mail.com  9666696518  Bangalore
1           11      Akash     Patel   akash11@mail.com  9719551111  Bangalore
2           16     Anjali     Singh  anjali16@mail.com  9118811611  Bangalore
3            2       Ritu       Das     ritu2@mail.com  9627404182  Bangalore

In [23]:
# Bonus Challenge:
run_sql("""SELECT *
FROM employees
WHERE first_name LIKE 'j%'
ORDER BY first_name ASC;""")

,employee_id,first_name,last_name,department_id,hire_date,salary,job_title,city,email
0,9,John,Brown,9,2021-11-22,45000.0,Data Engineer,Pune,john.brown9@company.com