<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day051sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [2]:
# Topic: LEFT JOIN - Introduction

In [3]:
#1
run_sql("""SELECT *
           FROM customers
           LEFT JOIN orders
           ON customers.customer_id = orders.customer_id;""")

,customer_id,first_name,last_name,email,phone,city,order_id,customer_id,product_id,order_date,quantity
0,1,Akash,Sharma,akash1@mail.com,9666696518,Bangalore,10.0,1.0,10.0,2024-07-16,5.0
1,2,Ritu,Das,ritu2@mail.com,9627404182,Bangalore,66.0,2.0,3.0,2024-08-03,4.0
2,2,Ritu,Das,ritu2@mail.com,9627404182,Bangalore,7.0,2.0,20.0,2024-05-15,2.0
3,2,Ritu,Das,ritu2@mail.com,9627404182,Bangalore,52.0,2.0,23.0,2026-01-31,4.0
4,3,Mohit,Kumar,mohit3@mail.com,9208428912,Mumbai,89.0,3.0,1.0,2026-03-29,1.0
...,...,...,...,...,...,...,...,...,...,...,...
103,36,Anjali,Gupta,anjali36@mail.com,9310837702,Chennai,NaN,NaN,NaN,None,NaN
104,37,Deepak,Wilson,deepak37@mail.com,9413891625,Pune,NaN,NaN,NaN,None,NaN
105,38,Komal,Roy,komal38@mail.com,9634822466,Chennai,NaN,NaN,NaN,None,NaN
106,39,Nitin,Das,nitin39@mail.com,9759424149,Chennai,NaN,NaN,NaN,None,NaN
107,40,Aisha,Taylor,aisha40@mail.com,9829603810,Kolkata,NaN,NaN,NaN,None,NaN

In [6]:
#2
run_sql("""SELECT *
           FROM departments
           LEFT JOIN employees
           ON departments.department_id = employees.department_id;""")

,department_id,department_name,manager_id,location,budget,employee_id,first_name,last_name,department_id,hire_date,salary,job_title,city,email
0,1,HR,1,Bangalore,300000.0,1,Aarav,Patel,1,2020-07-10,47500.0,HR Executive,Chennai,aarav.patel1@company.com
1,1,HR,1,Bangalore,300000.0,21,Arjun,Taylor,1,2021-09-03,42500.0,HR Executive,Bangalore,arjun.taylor21@company.com
2,1,HR,1,Bangalore,300000.0,11,Noah,Singh,1,2023-04-11,112500.0,HR Executive,Delhi,noah.singh11@company.com
3,2,Finance,2,Mumbai,450000.0,22,Isha,Roy,2,2022-08-14,60000.0,Accountant,Hyderabad,isha.roy22@company.com
4,2,Finance,2,Mumbai,450000.0,12,Olivia,Roy,2,2021-02-05,50000.0,Accountant,Bangalore,olivia.roy12@company.com
5,2,Finance,2,Mumbai,450000.0,2,Vivaan,Patel,2,2022-01-10,105000.0,Accountant,Bangalore,vivaan.patel2@company.com
6,3,IT,3,Bangalore,900000.0,3,Aditya,Das,3,2021-11-02,45000.0,Software Engineer,Delhi,aditya.das3@company.com
7,3,IT,3,Bangalore,900000.0,23,Kabir,Sharma,3,2023-05-02,105000.0,Software Engineer,Mumbai,kabir.sharma23@company.com
8,3,IT,3,Bangalore,900000.0,13,Liam,Singh,3,2020-10-03,105000.0,Software Engineer,Mumbai,liam.singh13@company.com
9,4,Marketing,4,Delhi,350000.0,24,Meera,Singh,4,2021-07-03,112500.0,Marketing Executive,Hyderabad,meera.singh24@company.com
10,4,Marketing,4,Delhi,350000.0,4,Riya,Das,4,2024-02-16,117500.0,Marketing Executive,Delhi,riya.das4@company.com
11,4,Marketing,4,Delhi,350000.0,14,Sophia,Roy,4,2022-01-01,97500.0,Marketing Executive,Delhi,sophia.roy14@company.com
12,5,Sales,5,Hyderabad,700000.0,15,Ananya,Singh,5,2022-08-02,72500.0,Sales Executive,Kolkata,ananya.singh15@company.com
13,5,Sales,5,Hyderabad,700000.0,5,Priya,Das,5,2020-01-29,120000.0,Sales Executive,Mumbai,priya.das5@company.com
14,5,Sales,5,Hyderabad,700000.0,25,Vikram,Roy,5,2024-11-20,57500.0,Sales Executive,Pune,vikram.roy25@company.com
15,6,Operations,6,Pune,500000.0,16,Karan,Taylor,6,2021-01-27,117500.0,Operations Analyst,Pune,karan.taylor16@company.com
16,6,Operations,6,Pune,500000.0,6,Neha,Taylor,6,2024-11-24,67500.0,Operations Analyst,Hyderabad,neha.taylor6@company.com
17,6,Operations,6,Pune,500000.0,26,Nisha,Sharma,6,2023-08-06,110000.0,Operations Analyst,Pune,nisha.sharma26@company.com
18,7,Support,7,Chennai,250000.0,27,Daniel,Roy,7,2023-05-29,60000.0,Support Engineer,Pune,daniel.roy27@company.com
19,7,Support,7,Chennai,250000.0,7,Rahul,Roy,7,2019-02-23,90000.0,Support Engineer,Mumbai,rahul.roy7@company.com
20,7,Support,7,Chennai,250000.0,17,Rohan,Singh,7,2022-04-21,52500.0,Support Engineer,Mumbai,rohan.singh17@company.com
21,8,Legal,8,Delhi,280000.0,8,Amit,Roy,8,2021-05-07,105000.0,Legal Advisor,Bangalore,amit.roy8@company.com
22,8,Legal,8,Delhi,280000.0,28,Grace,Brown,8,2023-03-29,40000.0,Legal Advisor,Bangalore,grace.brown28@company.com
23,8,Legal,8,Delhi,280000.0,18,Sneha,Sharma,8,2020-01-20,50000.0,Legal Advisor,Bangalore,sneha.sharma18@company.com
24,9,Data Engineering,9,Bangalore,800000.0,29,Aryan,Das,9,2022-12-19,70000.0,Data Engineer,Hyderabad,aryan.das29@company.com
25,9,Data Engineering,9,Bangalore,800000.0,19,David,Singh,9,2021-04-21,62500.0,Data Engineer,Pune,david.singh19@company.com
26,9,Data Engineering,9,Bangalore,800000.0,9,John,Brown,9,2021-11-22,45000.0,Data Engineer,Pune,john.brown9@company.com
27,10,Security,10,Kolkata,220000.0,10,Emma,Kumar,10,2023-07-25,97500.0,Security Analyst,Kolkata,emma.kumar10@company.com
28,10,Security,10,Kolkata,220000.0,30,Pooja,Sharma,10,2020-05-02,120000.0,Security Analyst,Pune,pooja.sharma30@company.com
29,10,Security,10,Kolkata,220000.0,20,Sara,Taylor,10,2023-12-21,85000.0,Security Analyst,Delhi,sara.taylor20@company.com

In [7]:
#3
# no supplier table

In [20]:
#4
run_sql("""SELECT *
        FROM products
        LEFT JOIN orders
        ON products.product_id = orders.product_id;""")

,product_id,product_name,category,price,stock_quantity,order_id,customer_id,product_id,order_date,quantity
0,1,Laptop Model 1,Laptop,90499.0,35,89,3,1,2026-03-29,1
1,1,Laptop Model 1,Laptop,90499.0,35,37,5,1,2025-12-31,4
2,1,Laptop Model 1,Laptop,90499.0,35,23,11,1,2024-02-08,2
3,1,Laptop Model 1,Laptop,90499.0,35,86,25,1,2024-07-25,4
4,1,Laptop Model 1,Laptop,90499.0,35,58,30,1,2026-04-06,4
...,...,...,...,...,...,...,...,...,...,...
95,24,Mouse Model 4,Mouse,2999.0,0,85,14,24,2024-12-26,4
96,24,Mouse Model 4,Mouse,2999.0,0,64,28,24,2024-06-12,3
97,24,Mouse Model 4,Mouse,2999.0,0,3,29,24,2024-01-15,3
98,25,Camera Model 1,Camera,46499.0,0,29,8,25,2026-03-15,1
99,25,Camera Model 1,Camera,46499.0,0,65,10,25,2025-10-12,4

In [17]:
#5
run_sql("""SELECT
           customers.customer_id,
           customers.first_name,
           customers.last_name,
           COUNT(orders.order_id) AS total_orders
           FROM customers
           LEFT JOIN orders
           ON customers.customer_id = orders.customer_id
           GROUP BY
           customers.customer_id,
           customers.first_name,
           customers.last_name;""")

    customer_id first_name last_name  total_orders
0             1      Akash    Sharma             1
1             2       Ritu       Das             3
2             3      Mohit     Kumar             3
3             4     Simran       Das             3
4             5       Yash    Sharma             3
5             6     Anjali     Singh             0
6             7     Deepak    Wilson             1
7             8      Komal       Roy             3
8             9      Nitin     Brown             4
9            10      Aisha     Kumar             2
10           11      Akash     Patel             3
11           12       Ritu     Kumar             1
12           13      Mohit       Das             6
13           14     Simran    Taylor             5
14           15       Yash    Sharma             5
15           16     Anjali     Singh             5
16           17     Deepak    Taylor             2
17           18      Komal     Singh             1
18           19      Nitin    Taylor             2
19           20      Aisha     Kumar             3
20           21      Akash    Sharma             0
21           22       Ritu     Kumar             0
22           23      Mohit    Taylor             1
23           24     Simran       Das             3
24           25       Yash     Singh             3
25           26     Anjali     Kumar             4
26           27     Deepak    Sharma             2
27           28      Komal     Singh             3
28           29      Nitin    Wilson             3
29           30      Aisha       Das             2
30           31      Akash     Gupta             1
31           32       Ritu    Sharma             7
32           33      Mohit       Roy             2
33           34     Simran    Wilson             8
34           35       Yash       Das             5
35           36     Anjali     Gupta             0
36           37     Deepak    Wilson             0
37           38      Komal       Roy             0
38           39      Nitin       Das             0
39           40      Aisha    Taylor             0

In [18]:
# Bonucs Challege
run_sql("""SELECT
           departments.department_id,
           departments.department_name,
           AVG(employees.salary) AS average_salary
           FROM departments
           LEFT JOIN employees
           ON departments.department_id = employees.department_id
           GROUP BY
          departments.department_id,
          departments.department_name;""")

   department_id   department_name  average_salary
0              1                HR    67500.000000
1              2           Finance    71666.666667
2              3                IT    85000.000000
3              4         Marketing   109166.666667
4              5             Sales    83333.333333
5              6        Operations    98333.333333
6              7           Support    67500.000000
7              8             Legal    65000.000000
8              9  Data Engineering    59166.666667
9             10          Security   100833.333333