<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day031sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [2]:
# Topic: Introduction to the COUNT() aggegate fuction.

In [3]:
#1 Count the total number of employees in the employees table.
run_sql("""SELECT COUNT(*) AS total_employees
FROM employees;""")

   total_employees
0               30

In [5]:
#2 Count the total number of departments.
run_sql("""SELECT COUNT(*) AS total_departments
FROM departments;""")

   total_departments
0                 10

In [6]:
#3 Count the total number of products.
run_sql("""SELECT COUNT(*) AS total_products
FROM products;""")

   total_products
0              25

In [7]:
#4 Count the total number of customers.
run_sql("""SELECT COUNT(*) total_customers
FROM customers;""")

   total_customers
0               40

In [8]:
#5 Count the total number of orders.
run_sql("""SELECT COUNT(*) AS total_orders
FROM ORDERS;""")

   total_orders
0           100

In [9]:
# Bouns Challege
run_sql("""SELECT COUNT(email) AS total_emails
FROM employees;""")

   total_emails
0            30