<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day020sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [2]:
# Topic: Final review of WHERE, AND, NOT,IN, and BETWEEEN.

In [8]:
#1 Display employees whose employee_id is BETWEEN 1 AND 10.
run_sql("""SELECT *
FROM employees
WHERE employee_id BETWEEN 1 AND 10;""")

,employee_id,first_name,last_name,department_id,hire_date,salary,job_title,city,email
0,1,Aarav,Patel,1,2020-07-10,47500.0,HR Executive,Chennai,aarav.patel1@company.com
1,2,Vivaan,Patel,2,2022-01-10,105000.0,Accountant,Bangalore,vivaan.patel2@company.com
2,3,Aditya,Das,3,2021-11-02,45000.0,Software Engineer,Delhi,aditya.das3@company.com
3,4,Riya,Das,4,2024-02-16,117500.0,Marketing Executive,Delhi,riya.das4@company.com
4,5,Priya,Das,5,2020-01-29,120000.0,Sales Executive,Mumbai,priya.das5@company.com
5,6,Neha,Taylor,6,2024-11-24,67500.0,Operations Analyst,Hyderabad,neha.taylor6@company.com
6,7,Rahul,Roy,7,2019-02-23,90000.0,Support Engineer,Mumbai,rahul.roy7@company.com
7,8,Amit,Roy,8,2021-05-07,105000.0,Legal Advisor,Bangalore,amit.roy8@company.com
8,9,John,Brown,9,2021-11-22,45000.0,Data Engineer,Pune,john.brown9@company.com
9,10,Emma,Kumar,10,2023-07-25,97500.0,Security Analyst,Kolkata,emma.kumar10@company.com

In [10]:
#2 Display customers whose city is NOT 'Delhi'.
run_sql("""SELECT *
FROM customers
WHERE city NOT IN ('Delhi');""")

    customer_id first_name last_name              email       phone       city
0             1      Akash    Sharma    akash1@mail.com  9666696518  Bangalore
1             2       Ritu       Das     ritu2@mail.com  9627404182  Bangalore
2             3      Mohit     Kumar    mohit3@mail.com  9208428912     Mumbai
3             4     Simran       Das   simran4@mail.com  9979444461    Chennai
4             5       Yash    Sharma     yash5@mail.com  9426111115       Pune
5             6     Anjali     Singh   anjali6@mail.com  9693986973       Pune
6             7     Deepak    Wilson   deepak7@mail.com  9906274295  Hyderabad
7             9      Nitin     Brown    nitin9@mail.com  9899533704  Hyderabad
8            10      Aisha     Kumar   aisha10@mail.com  9332083015    Chennai
9            11      Akash     Patel   akash11@mail.com  9719551111  Bangalore
10           13      Mohit       Das   mohit13@mail.com  9361812679  Hyderabad
11           14     Simran    Taylor  simran14@mail.com  9604314504    Kolkata
12           15       Yash    Sharma    yash15@mail.com  9702952921  Hyderabad
13           16     Anjali     Singh  anjali16@mail.com  9118811611  Bangalore
14           17     Deepak    Taylor  deepak17@mail.com  9865412201  Hyderabad
15           18      Komal     Singh   komal18@mail.com  9504584808    Kolkata
16           19      Nitin    Taylor   nitin19@mail.com  9995653703  Hyderabad
17           21      Akash    Sharma   akash21@mail.com  9124393190       Pune
18           22       Ritu     Kumar    ritu22@mail.com  9882449902  Hyderabad
19           23      Mohit    Taylor   mohit23@mail.com  9744597750    Kolkata
20           24     Simran       Das  simran24@mail.com  9185583902       Pune
21           25       Yash     Singh    yash25@mail.com  9834197053       Pune
22           28      Komal     Singh   komal28@mail.com  9110051432     Mumbai
23           29      Nitin    Wilson   nitin29@mail.com  9200774016  Hyderabad
24           30      Aisha       Das   aisha30@mail.com  9627755893     Mumbai
25           31      Akash     Gupta   akash31@mail.com  9750806415    Kolkata
26           32       Ritu    Sharma    ritu32@mail.com  9787498671    Chennai
27           34     Simran    Wilson  simran34@mail.com  9642604350       Pune
28           35       Yash       Das    yash35@mail.com  9847568100  Hyderabad
29           36     Anjali     Gupta  anjali36@mail.com  9310837702    Chennai
30           37     Deepak    Wilson  deepak37@mail.com  9413891625       Pune
31           38      Komal       Roy   komal38@mail.com  9634822466    Chennai
32           39      Nitin       Das   nitin39@mail.com  9759424149    Chennai
33           40      Aisha    Taylor   aisha40@mail.com  9829603810    Kolkata

In [12]:
#3
run_sql("""SELECT *
FROM products
WHERE category IN ('Electronic', 'Furniture')
AND price BETWEEN 1000 AND 5000;""")

Empty DataFrame
Columns: [product_id, product_name, category, price, stock_quantity]
Index: []

In [26]:
#4
run_sql("""SELECT *
FROM orders
WHERE customer_id IN (1, 2, 3)
AND product_id NOT IN (4, 5);
""")

   order_id  customer_id  product_id  order_date  quantity
0         7            2          20  2024-05-15         2
1        10            1          10  2024-07-16         5
2        52            2          23  2026-01-31         4
3        66            2           3  2024-08-03         4
4        80            3           6  2024-01-26         2
5        89            3           1  2026-03-29         1

In [23]:
#5
run_sql("""SELECT employee_id, first_name, last_name
FROM employees
WHERE department_id IN (1, 2, 3)
AND employee_id BETWEEN 2 AND 10;""")

   employee_id first_name last_name
0            2     Vivaan     Patel
1            3     Aditya       Das

In [28]:
# Bonus Challenge
run_sql("""SELECT *
FROM products
WHERE category IN ('Electronic', 'Furniture')
AND price BETWEEN 1000 AND 5000
AND stock_quantity NOT IN (0);""")

Empty DataFrame
Columns: [product_id, product_name, category, price, stock_quantity]
Index: []