<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day025sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [2]:
# Topic: Using LIKE to find that end with specific letters.

In [5]:
#1 Display all customers whose customer_name ends with the letter 'n'.
run_sql("""SELECT *
FROM customers
WHERE first_name LIKE '%n';""")

   customer_id first_name last_name              email       phone       city
0            4     Simran       Das   simran4@mail.com  9979444461    Chennai
1            9      Nitin     Brown    nitin9@mail.com  9899533704  Hyderabad
2           14     Simran    Taylor  simran14@mail.com  9604314504    Kolkata
3           19      Nitin    Taylor   nitin19@mail.com  9995653703  Hyderabad
4           24     Simran       Das  simran24@mail.com  9185583902       Pune
5           29      Nitin    Wilson   nitin29@mail.com  9200774016  Hyderabad
6           34     Simran    Wilson  simran34@mail.com  9642604350       Pune
7           39      Nitin       Das   nitin39@mail.com  9759424149    Chennai

In [6]:
#2 Display all employees whose first_naem ends with the letter 'a'.
run_sql("""SELECT *
FROM employees
WHERE first_name LIKE '%a';""")

,employee_id,first_name,last_name,department_id,hire_date,salary,job_title,city,email
0,3,Aditya,Das,3,2021-11-02,45000.0,Software Engineer,Delhi,aditya.das3@company.com
1,4,Riya,Das,4,2024-02-16,117500.0,Marketing Executive,Delhi,riya.das4@company.com
2,5,Priya,Das,5,2020-01-29,120000.0,Sales Executive,Mumbai,priya.das5@company.com
3,6,Neha,Taylor,6,2024-11-24,67500.0,Operations Analyst,Hyderabad,neha.taylor6@company.com
4,10,Emma,Kumar,10,2023-07-25,97500.0,Security Analyst,Kolkata,emma.kumar10@company.com
5,12,Olivia,Roy,2,2021-02-05,50000.0,Accountant,Bangalore,olivia.roy12@company.com
6,14,Sophia,Roy,4,2022-01-01,97500.0,Marketing Executive,Delhi,sophia.roy14@company.com
7,15,Ananya,Singh,5,2022-08-02,72500.0,Sales Executive,Kolkata,ananya.singh15@company.com
8,18,Sneha,Sharma,8,2020-01-20,50000.0,Legal Advisor,Bangalore,sneha.sharma18@company.com
9,20,Sara,Taylor,10,2023-12-21,85000.0,Security Analyst,Delhi,sara.taylor20@company.com
10,22,Isha,Roy,2,2022-08-14,60000.0,Accountant,Hyderabad,isha.roy22@company.com
11,24,Meera,Singh,4,2021-07-03,112500.0,Marketing Executive,Hyderabad,meera.singh24@company.com
12,26,Nisha,Sharma,6,2023-08-06,110000.0,Operations Analyst,Pune,nisha.sharma26@company.com
13,30,Pooja,Sharma,10,2020-05-02,120000.0,Security Analyst,Pune,pooja.sharma30@company.com

In [7]:
#3 Display all products whose product_name ends with the letter 'r'.
run_sql("""SELECT *
FROM products
WHERE product_name LIKE '%r';""")

Empty DataFrame
Columns: [product_id, product_name, category, price, stock_quantity]
Index: []

In [10]:
#4 Display all department whose department_naem ends with the letter 's'.
run_sql("""SELECT *
FROM  departments
WHERE department_name LIKE '%s';""")

   department_id department_name  manager_id   location    budget
0              5           Sales           5  Hyderabad  700000.0
1              6      Operations           6       Pune  500000.0

In [11]:
#5 Dsiplay all cutomers whose city ends with the letter'i'.
run_sql("""SELECT *
FROM customers
WHERE city LIKE '%i';""")

    customer_id first_name last_name              email       phone     city
0             3      Mohit     Kumar    mohit3@mail.com  9208428912   Mumbai
1             4     Simran       Das   simran4@mail.com  9979444461  Chennai
2             8      Komal       Roy    komal8@mail.com  9467566361    Delhi
3            10      Aisha     Kumar   aisha10@mail.com  9332083015  Chennai
4            12       Ritu     Kumar    ritu12@mail.com  9658448295    Delhi
5            20      Aisha     Kumar   aisha20@mail.com  9659589923    Delhi
6            26     Anjali     Kumar  anjali26@mail.com  9988357959    Delhi
7            27     Deepak    Sharma  deepak27@mail.com  9922832851    Delhi
8            28      Komal     Singh   komal28@mail.com  9110051432   Mumbai
9            30      Aisha       Das   aisha30@mail.com  9627755893   Mumbai
10           32       Ritu    Sharma    ritu32@mail.com  9787498671  Chennai
11           33      Mohit       Roy   mohit33@mail.com  9665152033    Delhi
12           36     Anjali     Gupta  anjali36@mail.com  9310837702  Chennai
13           38      Komal       Roy   komal38@mail.com  9634822466  Chennai
14           39      Nitin       Das   nitin39@mail.com  9759424149  Chennai

In [9]:
# Bonus Challege
run_sql("""SELECT *
FROM employees
WHERE last_name LIKE '%y';""")

,employee_id,first_name,last_name,department_id,hire_date,salary,job_title,city,email
0,7,Rahul,Roy,7,2019-02-23,90000.0,Support Engineer,Mumbai,rahul.roy7@company.com
1,8,Amit,Roy,8,2021-05-07,105000.0,Legal Advisor,Bangalore,amit.roy8@company.com
2,12,Olivia,Roy,2,2021-02-05,50000.0,Accountant,Bangalore,olivia.roy12@company.com
3,14,Sophia,Roy,4,2022-01-01,97500.0,Marketing Executive,Delhi,sophia.roy14@company.com
4,22,Isha,Roy,2,2022-08-14,60000.0,Accountant,Hyderabad,isha.roy22@company.com
5,25,Vikram,Roy,5,2024-11-20,57500.0,Sales Executive,Pune,vikram.roy25@company.com
6,27,Daniel,Roy,7,2023-05-29,60000.0,Support Engineer,Pune,daniel.roy27@company.com