<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day040sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [1]:
# Topic: Aggregate Funtion - Final Practice

In [6]:
#1 Display the total numbers of employees and the highest salary.
run_sql("""SELECT COUNT(*) AS total_employees,
           MAX(salary) AS highest_salary
           FROM employees;""")

   total_employees  highest_salary
0               30        120000.0

In [8]:
#2 Find the total stock quantity and the average product price from the products table.
run_sql("""SELECT SUM(stock_quantity) AS total_stock_quantity,
             AVG(price) AS average_price
             FROM products;""")

   total_stock_quantity  average_price
0                   572        26099.0

In [9]:
#3 Display the total number of orders, the minimum quantity , and the maximum quantiy ordered.
run_sql("""SELECT COUNT(*) AS total_orders,
         MIN(quantity) AS minimum_quantity,
         MAX(quantity) AS maximum_quantity
         FROM orders;""")

   total_orders  minimum_quantity  maximum_quantity
0           100                 1                 5

In [21]:
#4
run_sql("""SELECT COUNT(*) AS total_products,
                 SUM(stock_quantity) AS total_stock_quantity,
                 AVG(price) AS averge_price,
                 MIN(price) AS minimum_price,
                 MAX(price) AS highest_price
        FROM products
        WHERE category = 'Electronics';""")

,total_products,total_stock_quantity,averge_price,minimum_price,highest_price
0,0,None,None,None,None

In [15]:
#5
run_sql("""SELECT COUNT(*) AS total_employees,
         SUM(salary) AS total_salary,
         AVG(salary) AS average_salary,
         MIN(salary) AS minimum_salary,
         MAX(salary) AS maximum_salary
         FROM employees
         WHERE department_id = 3;""" )

,total_employees,total_salary,average_salary,minimum_salary,maximum_salary
0,3,255000.0,85000.0,45000.0,105000.0

In [19]:
# Bonus Challege
run_sql("""SELECT COUNT(*) AS total_orders,
           SUM(quantity) AS total_ordered_quantity,
           AVG(quantity) AS average_quantity,
           MIN(quantity) AS smallest_quantity,
           MAX(quantity) AS largest_quantity
           FROM orders;""")

,total_orders,total_ordered_quantity,average_quantity,smallest_quantity,largest_quantity
0,100,293,2.93,1,5