<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day038sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [2]:
# Topic: Using Multiple Aggregate Funtions Together

In [7]:
#1 Display the total number of employees and the minimum and miximum salary.
run_sql("""SELECT COUNT(*) AS total_employees,
                MIN(salary) AS minimum_salary,
                MAX(salary) AS maximum_salary
         FROM employees;""")

   total_employees  minimum_salary  maximum_salary
0               30         40000.0        120000.0

In [4]:
#2 Show the total number of products along with the minimum and maiximum product price.
run_sql("""SELECT COUNT(*) AS total_products,
         MIN(price) AS minimum_price,
         MAX(price) AS maximum_price
  FROM  products;""")

   total_products  minimum_price  maximum_price
0              25         1499.0        91999.0

In [5]:
#3 Display the total number of orderes, total orders, total ordered quantity, and average order quantity.
run_sql("""SELECT COUNT(*) AS total_orders,
      SUM(quantity) AS total_ordered_quantity,
      AVG(quantity) AS averge_order_quantity
 FROM orders;""")

   total_orders  total_ordered_quantity  averge_order_quantity
0           100                     293                   2.93

In [6]:
#4 For products in the Electronics category, display the total number of products, minimum price, maximum price, and average price.
run_sql("""SELECT COUNT(*) AS total_product,
    MIN(price) AS minimum_price,
    MAX(price) AS maximum_price,
    AVG(price) AS average_price
FROM products
WHERE category = 'Electronis'""")

   total_product minimum_price maximum_price average_price
0              0          None          None          None

In [13]:
#5 For employees in department_id = 2, display the total number of employees, total salary, average salary, minimum salary, and maximum salary.
run_sql("""SELECT COUNT(*) AS total_employees,
         SUM(salary) AS total_salary,
         AVG(salary) AS average_salary,
         MIN(salary) AS minimum_salary,
         MAX(salary) AS maximum_salary
   FROM employees
   WHERE department_id = 2;""")

,total_employees,total_salary,average_salary,minimum_salary,maximum_salary
0,3,215000.0,71666.666667,50000.0,105000.0

In [12]:
# Bonus Challege
run_sql("""SELECT COUNT(*) AS total_orders,
      MIN(order_date) AS earliest_order_date,
      MAX(order_date) AS latest_order_date
 FROM orders;""")

   total_orders earliest_order_date latest_order_date
0           100          2024-01-07        2026-05-02