<a href="https://colab.research.google.com/github/surbhi-codehub/100-Days-SQL-Journey/blob/main/day01sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [2]:
run_sql("SELECT name FROM sqlite_master WHERE type='table';")

          name
0  departments
1    employees
2     products
3    customers
4       orders

In [3]:
run_sql("""SELECT *
FROM employees;""")

,employee_id,first_name,last_name,department_id,hire_date,salary,job_title,city,email
0,1,Aarav,Patel,1,2020-07-10,47500.0,HR Executive,Chennai,aarav.patel1@company.com
1,2,Vivaan,Patel,2,2022-01-10,105000.0,Accountant,Bangalore,vivaan.patel2@company.com
2,3,Aditya,Das,3,2021-11-02,45000.0,Software Engineer,Delhi,aditya.das3@company.com
3,4,Riya,Das,4,2024-02-16,117500.0,Marketing Executive,Delhi,riya.das4@company.com
4,5,Priya,Das,5,2020-01-29,120000.0,Sales Executive,Mumbai,priya.das5@company.com
5,6,Neha,Taylor,6,2024-11-24,67500.0,Operations Analyst,Hyderabad,neha.taylor6@company.com
6,7,Rahul,Roy,7,2019-02-23,90000.0,Support Engineer,Mumbai,rahul.roy7@company.com
7,8,Amit,Roy,8,2021-05-07,105000.0,Legal Advisor,Bangalore,amit.roy8@company.com
8,9,John,Brown,9,2021-11-22,45000.0,Data Engineer,Pune,john.brown9@company.com
9,10,Emma,Kumar,10,2023-07-25,97500.0,Security Analyst,Kolkata,emma.kumar10@company.com
10,11,Noah,Singh,1,2023-04-11,112500.0,HR Executive,Delhi,noah.singh11@company.com
11,12,Olivia,Roy,2,2021-02-05,50000.0,Accountant,Bangalore,olivia.roy12@company.com
12,13,Liam,Singh,3,2020-10-03,105000.0,Software Engineer,Mumbai,liam.singh13@company.com
13,14,Sophia,Roy,4,2022-01-01,97500.0,Marketing Executive,Delhi,sophia.roy14@company.com
14,15,Ananya,Singh,5,2022-08-02,72500.0,Sales Executive,Kolkata,ananya.singh15@company.com
15,16,Karan,Taylor,6,2021-01-27,117500.0,Operations Analyst,Pune,karan.taylor16@company.com
16,17,Rohan,Singh,7,2022-04-21,52500.0,Support Engineer,Mumbai,rohan.singh17@company.com
17,18,Sneha,Sharma,8,2020-01-20,50000.0,Legal Advisor,Bangalore,sneha.sharma18@company.com
18,19,David,Singh,9,2021-04-21,62500.0,Data Engineer,Pune,david.singh19@company.com
19,20,Sara,Taylor,10,2023-12-21,85000.0,Security Analyst,Delhi,sara.taylor20@company.com
20,21,Arjun,Taylor,1,2021-09-03,42500.0,HR Executive,Bangalore,arjun.taylor21@company.com
21,22,Isha,Roy,2,2022-08-14,60000.0,Accountant,Hyderabad,isha.roy22@company.com
22,23,Kabir,Sharma,3,2023-05-02,105000.0,Software Engineer,Mumbai,kabir.sharma23@company.com
23,24,Meera,Singh,4,2021-07-03,112500.0,Marketing Executive,Hyderabad,meera.singh24@company.com
24,25,Vikram,Roy,5,2024-11-20,57500.0,Sales Executive,Pune,vikram.roy25@company.com
25,26,Nisha,Sharma,6,2023-08-06,110000.0,Operations Analyst,Pune,nisha.sharma26@company.com
26,27,Daniel,Roy,7,2023-05-29,60000.0,Support Engineer,Pune,daniel.roy27@company.com
27,28,Grace,Brown,8,2023-03-29,40000.0,Legal Advisor,Bangalore,grace.brown28@company.com
28,29,Aryan,Das,9,2022-12-19,70000.0,Data Engineer,Hyderabad,aryan.das29@company.com
29,30,Pooja,Sharma,10,2020-05-02,120000.0,Security Analyst,Pune,pooja.sharma30@company.com

In [4]:
run_sql("""SELECT *
FROM departments;""")

   department_id   department_name  manager_id   location    budget
0              1                HR           1  Bangalore  300000.0
1              2           Finance           2     Mumbai  450000.0
2              3                IT           3  Bangalore  900000.0
3              4         Marketing           4      Delhi  350000.0
4              5             Sales           5  Hyderabad  700000.0
5              6        Operations           6       Pune  500000.0
6              7           Support           7    Chennai  250000.0
7              8             Legal           8      Delhi  280000.0
8              9  Data Engineering           9  Bangalore  800000.0
9             10          Security          10    Kolkata  220000.0

In [6]:
run_sql("""SELECT first_name, last_name
FROM employees;""")

   first_name last_name
0       Aarav     Patel
1      Vivaan     Patel
2      Aditya       Das
3        Riya       Das
4       Priya       Das
5        Neha    Taylor
6       Rahul       Roy
7        Amit       Roy
8        John     Brown
9        Emma     Kumar
10       Noah     Singh
11     Olivia       Roy
12       Liam     Singh
13     Sophia       Roy
14     Ananya     Singh
15      Karan    Taylor
16      Rohan     Singh
17      Sneha    Sharma
18      David     Singh
19       Sara    Taylor
20      Arjun    Taylor
21       Isha       Roy
22      Kabir    Sharma
23      Meera     Singh
24     Vikram       Roy
25      Nisha    Sharma
26     Daniel       Roy
27      Grace     Brown
28      Aryan       Das
29      Pooja    Sharma

In [8]:
run_sql("""SELECT *
FROM products
LIMIT 5;""")

   product_id    product_name category    price  stock_quantity
0           1  Laptop Model 1   Laptop  90499.0              35
1           2  Laptop Model 2   Laptop  90999.0               0
2           3  Laptop Model 3   Laptop  91499.0              50
3           4  Laptop Model 4   Laptop  91999.0               5
4           5  Mobile Model 1   Mobile  30499.0              35

In [9]:
run_sql("""SELECT *
FROM customers
LIMIT 10;""")

   customer_id first_name last_name             email       phone       city
0            1      Akash    Sharma   akash1@mail.com  9666696518  Bangalore
1            2       Ritu       Das    ritu2@mail.com  9627404182  Bangalore
2            3      Mohit     Kumar   mohit3@mail.com  9208428912     Mumbai
3            4     Simran       Das  simran4@mail.com  9979444461    Chennai
4            5       Yash    Sharma    yash5@mail.com  9426111115       Pune
5            6     Anjali     Singh  anjali6@mail.com  9693986973       Pune
6            7     Deepak    Wilson  deepak7@mail.com  9906274295  Hyderabad
7            8      Komal       Roy   komal8@mail.com  9467566361      Delhi
8            9      Nitin     Brown   nitin9@mail.com  9899533704  Hyderabad
9           10      Aisha     Kumar  aisha10@mail.com  9332083015    Chennai