<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day036sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [2]:
#1 Find the lowest product price in the in the poducts table.
run_sql("""SELECT MIN(price)
FROM products;""")

   MIN(price)
0      1499.0

In [4]:
#2 Find the minimum salary amonge all employees.
run_sql("""SELECT MIN(salary)
FROM employees;""")

   MIN(salary)
0      40000.0

In [6]:
#3 Find the earliest order_date in the orders table.
run_sql("""SELECT MIN(order_date)
FROM orders;""")

  MIN(order_date)
0      2024-01-07

In [7]:
#4 Find the mininmum stock quantity for products in the Electronics category.
run_sql("""SELECT MIN(stock_quantity)
FROM products
WHERE category = 'Electronics';""")

  MIN(stock_quantity)
0                None

In [9]:
#5 Find the earliest hire date of employees whose  department_id is 3.
run_sql("""SELECT MIN(hire_date)
FROM employees
WHERE department_id = 3;""")

  MIN(hire_date)
0     2020-10-03

In [12]:
# Bonus Challege
run_sql("""SELECT MIN(quantity)
FROM orders
WHERE quantity > 1;""")

   MIN(quantity)
0              2