<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day032sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [2]:
# Topic: COUNT() with Conditions

In [3]:
#1 Count how many employees belong to the Sales department.
run_sql("""SELECT COUNT(*)
FROM employees
WHERE department_id = 1;""")

   COUNT(*)
0         3

In [5]:
#2 Count how many products have a price greater than 100.
run_sql("""SELECT COUNT(*)
FROM products
WHERE price > 100;""")

   COUNT(*)
0        25

In [7]:
#3 Count how many customers live in Delhi.
run_sql("""SELECT COUNT(*)
FROM customers
WHERE city = 'Delhi';""")

   COUNT(*)
0         6

In [6]:
#4 Count the number of orders where the quantity is greater than 3.
run_sql("""SELECT COUNT(*)
FROM orders
WHERE quantity > 3;""")

   COUNT(*)
0        39

In [8]:
#5 Count how many employees earn a salary greater than 60000 and belong to department 2.
run_sql("""SELECT COUNT(*)
FROM employees
WHERE salary > 60000
AND department_id = 2.""")

   COUNT(*)
0         1

In [9]:
# Bonus Challenge
run_sql("""SELECT COUNT(*)
FROM products
WHERE stock_quantity < 20;""")

   COUNT(*)
0        13