<a href="https://colab.research.google.com/github/surbhi-codehub/100-Days-SQL-Journey/blob/main/day6sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [2]:
#1 Display only the employee__id and first_name columns from teh first 5 rows of the employes table.
run_sql("""SELECT employee_id, first_name
FROM employees
LIMIT 5;""")

   employee_id first_name
0            1      Aarav
1            2     Vivaan
2            3     Aditya
3            4       Riya
4            5      Priya

In [3]:
#2 Display the departments_id and department_name columns from teh first 4 rows of the departments table.
run_sql("""SELECT department_id, department_name
FROM departments
LIMIT 4;""")

   department_id department_name
0              1              HR
1              2         Finance
2              3              IT
3              4       Marketing

In [5]:
#3 Dispaly the product_id, product_name, price columns from the first 6 rows of the products table.
run_sql("""SELECT product_id, product_name, price
FROM products
LIMIT 6;""")

   product_id    product_name    price
0           1  Laptop Model 1  90499.0
1           2  Laptop Model 2  90999.0
2           3  Laptop Model 3  91499.0
3           4  Laptop Model 4  91999.0
4           5  Mobile Model 1  30499.0
5           6  Mobile Model 2  30999.0

In [14]:
#4 Display the customer_id customer_name, and city columns from the first 8 rows  of  the customer table.
run_sql("""SELECT customer_id, first_name, city
FROM customers
LIMIT 8;""")

   customer_id first_name       city
0            1      Akash  Bangalore
1            2       Ritu  Bangalore
2            3      Mohit     Mumbai
3            4     Simran    Chennai
4            5       Yash       Pune
5            6     Anjali       Pune
6            7     Deepak  Hyderabad
7            8      Komal      Delhi

In [15]:
#5 Display the oreder_id,employee_id, and order_date columns from the first 10 rows of the orders table.

run_sql("""SELECT order_id, customer_id, order_date
FROM orders
LIMIT 10;""")

   order_id  customer_id  order_date
0         1           20  2025-10-15
1         2           11  2025-02-26
2         3           29  2024-01-15
3         4           17  2024-09-08
4         5           16  2024-12-14
5         6           15  2025-09-01
6         7            2  2024-05-15
7         8           13  2026-03-11
8         9           28  2025-01-10
9        10            1  2024-07-16