<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day027sq%3B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [2]:
# Topic: Using the single-character wildcard_with LIKE.

In [6]:
#1 Display customers whose customer_name starts with 'A' and has exactly one more charcter.
run_sql("""SELECT *
FROM customers
WHERE first_name LIKE 'A_';""")

Empty DataFrame
Columns: [customer_id, first_name, last_name, email, phone, city]
Index: []

In [9]:
#2 Display employees whose first_name has exactly five characters.
run_sql("""SELECT *
FROM employees
WHERE first_name LIKE'___';""")

Empty DataFrame
Columns: [employee_id, first_name, last_name, department_id, hire_date, salary, job_title, city, email]
Index: []

In [10]:
#3 Display product_name starts with 'S' followed by exactly one charcter and then any remaining charcters.
run_sql("""SELECT *
FROM products
WHERE product_name LIKE 'S_%';""")

Empty DataFrame
Columns: [product_id, product_name, category, price, stock_quantity]
Index: []

In [11]:
#4 Display departments whose department_name has 'e' as the second charcter.
run_sql("""SELECT *
FROM departments
WHERE department_name LIKE '_e%';""")

   department_id department_name  manager_id location    budget
0              8           Legal           8    Delhi  280000.0
1             10        Security          10  Kolkata  220000.0

In [12]:
#5 Find customers whose city start with 'B', has exactly one unknown charcter, and then any remaining characters.
run_sql("""SELECT *
FROM customers
WHERE city LIKE 'B_%'""")

   customer_id first_name last_name              email       phone       city
0            1      Akash    Sharma    akash1@mail.com  9666696518  Bangalore
1            2       Ritu       Das     ritu2@mail.com  9627404182  Bangalore
2           11      Akash     Patel   akash11@mail.com  9719551111  Bangalore
3           16     Anjali     Singh  anjali16@mail.com  9118811611  Bangalore

In [13]:
# Bonus Challenge:
run_sql("""SELECT *
FROM employees
WHERE last_name LIKE 'J_%';""")

Empty DataFrame
Columns: [employee_id, first_name, last_name, department_id, hire_date, salary, job_title, city, email]
Index: []