<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day041sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [2]:
# Topic: Learn how to group rows with the same value and calculate summaries for each group.

In [5]:
#1 Display the number of employees in each department_id.
run_sql("""SELECT department_id, COUNT(*) AS employees_count
FROM employees
GROUP BY department_id;""")

   department_id  employees_count
0              1                3
1              2                3
2              3                3
3              4                3
4              5                3
5              6                3
6              7                3
7              8                3
8              9                3
9             10                3

In [6]:
#2 Display the number of products in each product category.
run_sql("""SELECT category, COUNT(*) AS product_count
FROM products
GROUP BY category;""")

     category  product_count
0      Camera              1
1  Headphones              4
2    Keyboard              4
3      Laptop              4
4      Mobile              4
5     Monitor              4
6       Mouse              4

In [7]:
#3 Display the stock quantity for each product category.
run_sql("""SELECT category, (stock_quantity) AS  total_stock
FROM products
GROUP BY category;""")

     category  total_stock
0      Camera            0
1  Headphones           80
2    Keyboard           80
3      Laptop           35
4      Mobile           35
5     Monitor           20
6       Mouse            0

In [8]:
#4 Display the average salary for each department_id.
run_sql("""SELECT department_id, AVG(salary) AS aveage_salary
FROM employees
GROUP BY  department_id;""")

   department_id  aveage_salary
0              1   67500.000000
1              2   71666.666667
2              3   85000.000000
3              4  109166.666667
4              5   83333.333333
5              6   98333.333333
6              7   67500.000000
7              8   65000.000000
8              9   59166.666667
9             10  100833.333333

In [11]:
#5 Display the total number of orders and the total ordered quantity for each customer.
run_sql("""SELECT customer_id,
        COUNT(*) AS total_orders,
        SUM(quantity) AS total_ordered_quantity
        FROM orders
        GROUP BY customer_id;""")

    customer_id  total_orders  total_ordered_quantity
0             1             1                       5
1             2             3                      10
2             3             3                       4
3             4             3                       7
4             5             3                      10
5             7             1                       4
6             8             3                       7
7             9             4                      17
8            10             2                       7
9            11             3                       6
10           12             1                       2
11           13             6                      16
12           14             5                      14
13           15             5                      17
14           16             5                      13
15           17             2                       8
16           18             1                       5
17           19             2                       5
18           20             3                      11
19           23             1                       3
20           24             3                      15
21           25             3                       9
22           26             4                      10
23           27             2                       5
24           28             3                       5
25           29             3                       9
26           30             2                       9
27           31             1                       3
28           32             7                      20
29           33             2                       2
30           34             8                      19
31           35             5                      16

In [12]:
# Bonus Challege
run_sql("""SELECT category,
     MIN(price) AS minimum_price,
     MAX(price) AS maximum_price
     FROM products
     GROUP BY category;""")

     category  minimum_price  maximum_price
0      Camera        46499.0        46499.0
1  Headphones         5499.0         6999.0
2    Keyboard         2499.0         3999.0
3      Laptop        90499.0        91999.0
4      Mobile        30499.0        31999.0
5     Monitor        16499.0        17999.0
6       Mouse         1499.0         2999.0