<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day049sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [2]:
# INNER JOIN with Multiple Tables

In [6]:
#1 Display each order along with the customer name.
run_sql("""SELECT orders.*, customers.first_name
        FROM orders
        INNER JOIN customers
        ON orders.customer_id = customers.customer_id;""")

    order_id  customer_id  product_id  order_date  quantity first_name
0          1           20           2  2025-10-15         4      Aisha
1          2           11          16  2025-02-26         2      Akash
2          3           29          24  2024-01-15         3      Nitin
3          4           17          23  2024-09-08         5     Deepak
4          5           16           3  2024-12-14         1     Anjali
..       ...          ...         ...         ...       ...        ...
95        96           24           8  2026-03-28         5     Simran
96        97           32          11  2024-10-06         2       Ritu
97        98           35           8  2025-02-24         2       Yash
98        99            4          23  2024-09-19         1     Simran
99       100           32          17  2024-07-13         5       Ritu

[100 rows x 6 columns]

In [7]:
#2. Display each product together with its supplier name.

# no supplier table.

In [8]:
#3 Display each employee along with the department name.
run_sql("""SELECT employees.*, departments.department_name
FROM employees
INNER JOIN departments
ON employees.department_id = departments.department_id;""")

,employee_id,first_name,last_name,department_id,hire_date,salary,job_title,city,email,department_name
0,1,Aarav,Patel,1,2020-07-10,47500.0,HR Executive,Chennai,aarav.patel1@company.com,HR
1,2,Vivaan,Patel,2,2022-01-10,105000.0,Accountant,Bangalore,vivaan.patel2@company.com,Finance
2,3,Aditya,Das,3,2021-11-02,45000.0,Software Engineer,Delhi,aditya.das3@company.com,IT
3,4,Riya,Das,4,2024-02-16,117500.0,Marketing Executive,Delhi,riya.das4@company.com,Marketing
4,5,Priya,Das,5,2020-01-29,120000.0,Sales Executive,Mumbai,priya.das5@company.com,Sales
5,6,Neha,Taylor,6,2024-11-24,67500.0,Operations Analyst,Hyderabad,neha.taylor6@company.com,Operations
6,7,Rahul,Roy,7,2019-02-23,90000.0,Support Engineer,Mumbai,rahul.roy7@company.com,Support
7,8,Amit,Roy,8,2021-05-07,105000.0,Legal Advisor,Bangalore,amit.roy8@company.com,Legal
8,9,John,Brown,9,2021-11-22,45000.0,Data Engineer,Pune,john.brown9@company.com,Data Engineering
9,10,Emma,Kumar,10,2023-07-25,97500.0,Security Analyst,Kolkata,emma.kumar10@company.com,Security
10,11,Noah,Singh,1,2023-04-11,112500.0,HR Executive,Delhi,noah.singh11@company.com,HR
11,12,Olivia,Roy,2,2021-02-05,50000.0,Accountant,Bangalore,olivia.roy12@company.com,Finance
12,13,Liam,Singh,3,2020-10-03,105000.0,Software Engineer,Mumbai,liam.singh13@company.com,IT
13,14,Sophia,Roy,4,2022-01-01,97500.0,Marketing Executive,Delhi,sophia.roy14@company.com,Marketing
14,15,Ananya,Singh,5,2022-08-02,72500.0,Sales Executive,Kolkata,ananya.singh15@company.com,Sales
15,16,Karan,Taylor,6,2021-01-27,117500.0,Operations Analyst,Pune,karan.taylor16@company.com,Operations
16,17,Rohan,Singh,7,2022-04-21,52500.0,Support Engineer,Mumbai,rohan.singh17@company.com,Support
17,18,Sneha,Sharma,8,2020-01-20,50000.0,Legal Advisor,Bangalore,sneha.sharma18@company.com,Legal
18,19,David,Singh,9,2021-04-21,62500.0,Data Engineer,Pune,david.singh19@company.com,Data Engineering
19,20,Sara,Taylor,10,2023-12-21,85000.0,Security Analyst,Delhi,sara.taylor20@company.com,Security
20,21,Arjun,Taylor,1,2021-09-03,42500.0,HR Executive,Bangalore,arjun.taylor21@company.com,HR
21,22,Isha,Roy,2,2022-08-14,60000.0,Accountant,Hyderabad,isha.roy22@company.com,Finance
22,23,Kabir,Sharma,3,2023-05-02,105000.0,Software Engineer,Mumbai,kabir.sharma23@company.com,IT
23,24,Meera,Singh,4,2021-07-03,112500.0,Marketing Executive,Hyderabad,meera.singh24@company.com,Marketing
24,25,Vikram,Roy,5,2024-11-20,57500.0,Sales Executive,Pune,vikram.roy25@company.com,Sales
25,26,Nisha,Sharma,6,2023-08-06,110000.0,Operations Analyst,Pune,nisha.sharma26@company.com,Operations
26,27,Daniel,Roy,7,2023-05-29,60000.0,Support Engineer,Pune,daniel.roy27@company.com,Support
27,28,Grace,Brown,8,2023-03-29,40000.0,Legal Advisor,Bangalore,grace.brown28@company.com,Legal
28,29,Aryan,Das,9,2022-12-19,70000.0,Data Engineer,Hyderabad,aryan.das29@company.com,Data Engineering
29,30,Pooja,Sharma,10,2020-05-02,120000.0,Security Analyst,Pune,pooja.sharma30@company.com,Security

In [10]:
#4 Display each order with the customer name and product name.
run_sql("""SELECT orders.*, customers.first_name, products.product_name
        FROM orders
        INNER JOIN customers
        ON orders.customer_id = customers.customer_id
        INNER JOIN products
        ON orders.product_id = products.product_id;""")

,order_id,customer_id,product_id,order_date,quantity,first_name,product_name
0,1,20,2,2025-10-15,4,Aisha,Laptop Model 2
1,2,11,16,2025-02-26,2,Akash,Monitor Model 4
2,3,29,24,2024-01-15,3,Nitin,Mouse Model 4
3,4,17,23,2024-09-08,5,Deepak,Mouse Model 3
4,5,16,3,2024-12-14,1,Anjali,Laptop Model 3
...,...,...,...,...,...,...,...
95,96,24,8,2026-03-28,5,Simran,Mobile Model 4
96,97,32,11,2024-10-06,2,Ritu,Headphones Model 3
97,98,35,8,2025-02-24,2,Yash,Mobile Model 4
98,99,4,23,2024-09-19,1,Simran,Mouse Model 3
99,100,32,17,2024-07-13,5,Ritu,Keyboard Model 1

In [12]:
#5 Display each customer with the total number of orders placed using INNER JOIN and GROUP BY.
run_sql("""SELECT customers.*, COUNT(orders.order_id) AS total_orders
        FROM customers
        INNER JOIN orders
        ON customers.customer_id = orders.customer_id
        GROUP BY customers.first_name;""")

,customer_id,first_name,last_name,email,phone,city,total_orders
0,20,Aisha,Kumar,aisha20@mail.com,9659589923,Delhi,7
1,11,Akash,Patel,akash11@mail.com,9719551111,Bangalore,5
2,16,Anjali,Singh,anjali16@mail.com,9118811611,Bangalore,9
3,17,Deepak,Taylor,deepak17@mail.com,9865412201,Hyderabad,5
4,28,Komal,Singh,komal28@mail.com,9110051432,Mumbai,7
5,13,Mohit,Das,mohit13@mail.com,9361812679,Hyderabad,12
6,29,Nitin,Wilson,nitin29@mail.com,9200774016,Hyderabad,9
7,2,Ritu,Das,ritu2@mail.com,9627404182,Bangalore,11
8,14,Simran,Taylor,simran14@mail.com,9604314504,Kolkata,19
9,15,Yash,Sharma,yash15@mail.com,9702952921,Hyderabad,16

In [13]:
# Bonus Challege
run_sql("""SELECT d.department_name, AVG(e.salary) AS average_salary
        FROM departments d
        INNER JOIN employees e
        ON d.department_id = e.department_id
        GROUP BY d.department_name;""")

    department_name  average_salary
0  Data Engineering    59166.666667
1           Finance    71666.666667
2                HR    67500.000000
3                IT    85000.000000
4             Legal    65000.000000
5         Marketing   109166.666667
6        Operations    98333.333333
7             Sales    83333.333333
8          Security   100833.333333
9           Support    67500.000000