<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day034sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [2]:
#1 Find the total quanity of all orders.
run_sql("""SELECT SUM(quantity) AS total_quantity
FROM orders;""")

   total_quantity
0             293

In [6]:
#2 Find the total stock quanity of all products.
run_sql("""SELECT SUM(stock_quantity) AS total_stock_quantity
FROM products;""")

   total_stock_quantity
0                   572

In [7]:
#3 Find the total salary of employees whose department_id is 1.
run_sql("""SELECT SUM(salary) AS total_salary
FROM employees
WHERE department_id = 1;""")

   total_salary
0      202500.0

In [8]:
#4 Find the total quantity orderd where the order quantity is greater than 2.
run_sql("""SELECT SUM(quantity) AS total_quantity
FROM orders
WHERE quantity > 2;""")

   total_quantity
0             227

In [10]:
#5 Find the total price of all products in the Electronics category.
run_sql("""SELECT SUM(price) AS total_price
FROM products
WHERE category = 'Electronics';""")

  total_price
0        None

In [12]:
# Bonus Challenge
run_sql("""SELECT SUM(salary) AS total_salary
FROM employees
WHERE hire_date > '2022-01-01';""")

   total_salary
0     1212500.0