<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day024sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [2]:
# Topic: Finding text using the LIKE operator.

In [6]:
#1 Display all customers whose customer_name starts with  the letter 'A'.
run_sql("""SELECT *
FROM customers
WHERE first_name LIKE 'A%';""")

    customer_id first_name last_name              email       phone       city
0             1      Akash    Sharma    akash1@mail.com  9666696518  Bangalore
1             6     Anjali     Singh   anjali6@mail.com  9693986973       Pune
2            10      Aisha     Kumar   aisha10@mail.com  9332083015    Chennai
3            11      Akash     Patel   akash11@mail.com  9719551111  Bangalore
4            16     Anjali     Singh  anjali16@mail.com  9118811611  Bangalore
5            20      Aisha     Kumar   aisha20@mail.com  9659589923      Delhi
6            21      Akash    Sharma   akash21@mail.com  9124393190       Pune
7            26     Anjali     Kumar  anjali26@mail.com  9988357959      Delhi
8            30      Aisha       Das   aisha30@mail.com  9627755893     Mumbai
9            31      Akash     Gupta   akash31@mail.com  9750806415    Kolkata
10           36     Anjali     Gupta  anjali36@mail.com  9310837702    Chennai
11           40      Aisha    Taylor   aisha40@mail.com  9829603810    Kolkata

In [7]:
#2 Display all employees whose first_name starts with the letter 'J'.
run_sql("""SELECT *
FROM employees
WHERE first_name LIKE 'J%';""")

,employee_id,first_name,last_name,department_id,hire_date,salary,job_title,city,email
0,9,John,Brown,9,2021-11-22,45000.0,Data Engineer,Pune,john.brown9@company.com

In [8]:
#3 Display all products whos products_name starts with the letter 'S'.
run_sql("""SELECT *
FROM products
WHERE product_name LIKE 'S%';""")

Empty DataFrame
Columns: [product_id, product_name, category, price, stock_quantity]
Index: []

In [9]:
#4 Display all department whose department_name starts with the letter 'H'.
run_sql("""SELECT *
FROM departments
WHERE department_name LIKE 'H%';""")

   department_id department_name  manager_id   location    budget
0              1              HR           1  Bangalore  300000.0

In [10]:
#5 Display all customers whose city starts with  the letter 'B'.
run_sql("""SELECT *
FROM customers
WHERE city LIKE 'B%';""")

   customer_id first_name last_name              email       phone       city
0            1      Akash    Sharma    akash1@mail.com  9666696518  Bangalore
1            2       Ritu       Das     ritu2@mail.com  9627404182  Bangalore
2           11      Akash     Patel   akash11@mail.com  9719551111  Bangalore
3           16     Anjali     Singh  anjali16@mail.com  9118811611  Bangalore

In [12]:
# Bonus Challenge:
# Choose any text column inthe database and find all values that start with a letter of your choice using LIKE.
run_sql("""SELECT *
FROM customers
WHERE first_name LIKE 'M%';""")

   customer_id first_name last_name             email       phone       city
0            3      Mohit     Kumar   mohit3@mail.com  9208428912     Mumbai
1           13      Mohit       Das  mohit13@mail.com  9361812679  Hyderabad
2           23      Mohit    Taylor  mohit23@mail.com  9744597750    Kolkata
3           33      Mohit       Roy  mohit33@mail.com  9665152033      Delhi