<a href="https://colab.research.google.com/github/surbhi-codehub/100-Days-SQL-Journey/blob/main/day5sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [3]:
#1 Display the first 3 rows from the departments table.
run_sql("""SELECT *
FROM departments
LIMIT 3;""")

   department_id department_name  manager_id   location    budget
0              1              HR           1  Bangalore  300000.0
1              2         Finance           2     Mumbai  450000.0
2              3              IT           3  Bangalore  900000.0

In [4]:
#2 Display first_name and last_name from the first 5 employees.
run_sql("""SELECT first_name, last_name
FROM employees
LIMIT 5;""")

  first_name last_name
0      Aarav     Patel
1     Vivaan     Patel
2     Aditya       Das
3       Riya       Das
4      Priya       Das

In [5]:
#3 Display product_name and price from the first 8 products.
run_sql("""SELECT product_name, price
FROM products
LIMIT 8;""")

     product_name    price
0  Laptop Model 1  90499.0
1  Laptop Model 2  90999.0
2  Laptop Model 3  91499.0
3  Laptop Model 4  91999.0
4  Mobile Model 1  30499.0
5  Mobile Model 2  30999.0
6  Mobile Model 3  31499.0
7  Mobile Model 4  31999.0

In [8]:
#4 Display customer_name and city from the first 10 customers.
run_sql("""SELECT first_name, last_name
FROM customers
LIMIT 10;""")

  first_name last_name
0      Akash    Sharma
1       Ritu       Das
2      Mohit     Kumar
3     Simran       Das
4       Yash    Sharma
5     Anjali     Singh
6     Deepak    Wilson
7      Komal       Roy
8      Nitin     Brown
9      Aisha     Kumar

In [11]:
#5 Display order _id , customer_id and order_date from the first 12 orders.
run_sql("""SELECT order_id, customer_id, order_date
FROM orders
LIMIT 12;""")

    order_id  customer_id  order_date
0          1           20  2025-10-15
1          2           11  2025-02-26
2          3           29  2024-01-15
3          4           17  2024-09-08
4          5           16  2024-12-14
5          6           15  2025-09-01
6          7            2  2024-05-15
7          8           13  2026-03-11
8          9           28  2025-01-10
9         10            1  2024-07-16
10        11           13  2024-12-19
11        12           26  2025-12-07

In [12]:
# Bonus Challenge
run_sql("""SELECT employee_id, first_name, last_name
FROM employees
LIMIT 7;""")

   employee_id first_name last_name
0            1      Aarav     Patel
1            2     Vivaan     Patel
2            3     Aditya       Das
3            4       Riya       Das
4            5      Priya       Das
5            6       Neha    Taylor
6            7      Rahul       Roy